name: Hello World Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:		


jobs:
  hello:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.0
        run: |
          python filterData.py
