name: Hello World Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:		


jobs:
  hello:
    runs-on: self-hosted
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

#       - name: setup python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'
      
      - name: setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

#       - name: install python packages
#         run: |
#           python -m pip install --upgrade pip
#           pip install pylint


#       - name: execute py script
#         run:
#           python filterData.py
#           pylint filterData.py
